version: '3.8'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "2181" ]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://127.0.0.1:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 72 # удаление сообщений через 72 часа
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_CLEANUP_POLICY: delete
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka
  
  pg_ml:
    container_name: pg_ml
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ml_db
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    ports:
      - "5488:5432"
    volumes:
      - ./ml_monitoring_services/pg_ml:/var/lib/postgresql/data

  grafana:
    container_name: grafana_1
    image: grafana/grafana:latest
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3111:3000"
    volumes:
      - ./ml_monitoring_services/grafana:/var/lib/grafana

  s3:
    container_name: s3
    image: minio/minio
    restart: always
    ports:
      - "9006:9000"
      - "9005:9001"
    volumes:
      - ./ml_monitoring_services/s3_storage:/data
    environment:
      MINIO_ACCESS_KEY: s3_access_key
      MINIO_SECRET_KEY: s3_secret_key
    command: server /data --console-address ":9001"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ml_monitoring_services/prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - cadvisor
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - ./ml_monitoring_services/cadvisor:/rootfs:ro
    - ./ml_monitoring_services/cadvisor/var/run:/var/run:rw
    - ./ml_monitoring_services/cadvisor/sys:/sys:ro
    - ./ml_monitoring_services/cadvisor/var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379

volumes:
  pg_data_wh:
  pg_grafana:
  grafana:
  s3:
  prometheus:
  cadvisor: