{
 "title": "Tables demonstration",
 "time": { "from": "2024-03-18T00:35:21.253Z", "to": "2024-03-18T12:35:21.253Z" },
 "panels": [
  {
   "title": "total_results",
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM total_results" }
   ]
  },
  {
   "title": "ml_model",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM ml_model  " }
   ]
  },
  {
   "title": "results",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 12 },
   "targets": [
    { "rawSql": "SELECT * FROM results " }
   ]
  }
 ]
}